site_name: ViyaDB
site_description: In-Memory Analytical Database
site_favicon: 'img/favicon.png'
google_analytics:
  - 'UA-23508932-8'
  - 'auto'
pages:
  - index.md
  - usage.md
  - samples.md
extra:
  logo: 'img/logo.svg'
  social:
    - type: 'github'
      link: 'https://github.com/viyadb'
    - type: 'twitter'
      link: 'https://twitter.com/viyadb'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/18228559'
  palette:
    primary: 'blue grey'
    accent: 'cyan'
theme: 'material'
markdown_extensions:
  - codehilite
  - toc(permalink=true)
  - admonition
