site_name: ViyaDB
site_description: In-Memory Analytical Database
site_url: 'https://viyadb.com'
repo_name: 'viyadb/viyadb'
repo_url: 'https://github.com/viyadb/viyadb'
edit_uri: ''
google_analytics:
  - 'UA-23508932-8'
  - 'auto'
pages:
  - Overview: index.md
  - Core Usage: usage.md
  - Setting Up a Cluster: clustering.md
  - Real-time Analytics: realtime.md
  - Examples: samples.md
theme:
  name: 'material'
  logo: 'img/logo.svg'
  favicon: 'img/favicon.png'
  palette:
    primary: 'blue grey'
    accent: 'cyan'
  social:
    - type: 'github'
      link: 'https://github.com/viyadb'
    - type: 'twitter'
      link: 'https://twitter.com/viyadb'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/18228559'
    - type: 'google'
      link: 'https://groups.google.com/forum/#!forum/viyadb'
    - type: 'envelope'
      link: 'mailto:michael@viyadb.com'
markdown_extensions:
  - codehilite
  - toc(permalink=true)
  - admonition
extra_css:
  - 'css/extra.css'
extra_javascript:
  - 'js/extra.js'
